title: Extending Affordance Templates to Support Remote Robot Activities
description: |-
  Michael W. Lanighan and Kenji Brameld
  IEEE iSpaRo 2025
  Workshop on Sustainable Space Robotics
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
github:
  is_project_page: false
